apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qlt-router.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "qlt-router.name" . }}
    helm.sh/chart: {{ include "qlt-router.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "qlt-router.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "qlt-router.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SENTINEL_ADDR
              value: "{{ .Values.service.sentinel.addr }}"

            - name: QLTS_PORT
              value: "{{ .Values.service.lumberjack.port }}"
            - name: QLTS_CERT
              value: "/var/run/certs/cert.pem"
            - name: QLTS_KEY
              value: "/var/run/certs/cert.key"
            #- name: QLTS_CA
            #  value: "/var/run/certs/ca.pem"

            - name: LUMBERJACK_ADDR
              value: "{{ .Values.service.lumberjack.addr }}"
            - name: LUMBERJACK_CERT
              value: "/var/run/lumberjack/cert.pem"
            - name: LUMBERJACK_KEY
              value: "/var/run/lumberjack/cert.key"
            - name: LUMBERJACK_CA
              value: "/var/run/lumberjack/ca.pem"

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: qlt
              containerPort: 3333
              protocol: TCP
            - name: qlts
              containerPort: 3334
              protocol: TCP
          volumeMounts:
            - name: certs
              mountPath: /var/run/certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: certs
        secret:
          secretName: {{ template "qlt-router.name" . }}-certs
      - name: lumberjack
        secret:
          secretName: {{ template "qlt-router.name" . }}-lumberjack
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
