variables:
  NAME: qlt-router
  DOCKER_REPO: sentineleventrouter-docker-snapshot-ptx.artifactory-ptx.ecd.axway.int
  RPM_REPO: https://artifactory-ptx.ecd.axway.int/artifactory/sentineleventrouter-generic-snapshot-ptx
  CURL_IMAGE: "davinci1976/docker-ci:unstable"
  CURL_AXWAY: "curl --cacert ./AxwayRootCA.cer"

#include:
#  - template: Code-Quality.gitlab-ci.yml

default:
  tags:
    - docker-ex

stages:
  - prepare
  - build
  - pack
  - test
  - deploy
  - security

version:
  image: davinci1976/docker-ci:unstable
  stage: prepare
  script:
    - ./scripts/setVersion.sh
  artifacts:
    paths:
      - ./.env

unit-test:
  image: docker
  needs: []
  stage: prepare
  #coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"
  script:
    - ./scripts/run-unit-test-docker.sh

.build:
  image: golang:buster
  stage: build
  needs:
    - version
    - unit-test
  cache:
    paths:
      - .cache/
    key: GO
  script:
    - (test -d /artefacts && ln -s /artefacts ./artefacts) || mkdir -p artefacts
    - ls -l .cache || true
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - make build-glibc
    - ./$NAME version
    - cp $NAME ./artefacts/
  artifacts:
    paths:
      - ./artefacts/$NAME
    expire_in: 2 day

build-glibc:
  image: docker
  stage: build
  needs:
    - version
  script:
    - (test -d /artefacts && ln -s /artefacts ./artefacts) || mkdir -p artefacts
    - ./scripts/run-build-docker.sh
    - chmod +x $NAME
    - cp $NAME ./artefacts/
  artifacts:
    paths:
      - ./artefacts/$NAME

build-docker:
  image: davinci1976/docker-ci:unstable
  stage: build
  needs:
    - version
    - unit-test
  script:
    - DOCKER_IMAGE=$NAME:$CI_COMMIT_BRANCH
    - docker build --pull -f ./Dockerfile -t $DOCKER_IMAGE .
    - docker run --rm $DOCKER_IMAGE $NAME version

integration-test-reset:
  image: docker
  needs: []
  when: manual
  stage: test
  #coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"
  script:
    - ./scripts/run-integration-test-docker.sh reset
  artifacts:
    when: always
    reports:
      junit: report.xml
      #coverage_report:
      #  coverage_format: cobertura
      #  path: coverage.xml

integration-test:
  image: docker
  needs:
    - build-docker
  stage: test
  cache:
    paths:
      - .cache/
    key: GO
  coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"
  script:
    - ./scripts/run-integration-test-docker.sh
  artifacts:
    when: always
    paths:
      - coverage.svg
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

rpm-build:
  image: rpmbuild/centos7
  needs:
    - version
    - build-glibc
  stage: pack
  script:
    - test -d /artefacts && ln -s /artefacts ./artefacts
    - . ./.env
    - ./rpm/rpm-build.sh $NAME $VERSION
  artifacts:
    paths:
      - ./artefacts/$NAME*.rpm
    expire_in: 2 day

rpm-test:
  image: davinci1976/docker-ci:unstable
  needs:
    - version
    - rpm-build
  stage: test
  script:
    #- test ! -e ./artefacts && ln -s /artefacts ./artefacts
    - test ! -e ./artefacts && cp -rf /artefacts ./artefacts/
    - ./rpm/rpm-test.sh $NAME

rpm-snapshot:
  image: $CURL_IMAGE
  stage: deploy
  dependencies:
    - version
    - rpm-build
  script:
    - . ./.env
    - CI_COMMIT_BRANCH=$(echo "$CI_COMMIT_BRANCH" | tr '[:upper:]' '[:lower:]')
    - $CURL_AXWAY -k -v -u $ARTIFACTORY_USER:$ARTIFACTORY_TOKEN -T ./artefacts/$NAME*.rpm "$RPM_REPO/$NAME/$NAME-$CI_COMMIT_BRANCH.rpm"

docker-snapshot:
  image: docker
  stage: deploy
  dependencies:
    - version
  before_script:
    - docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_TOKEN $DOCKER_REPO
    - . ./.env
  script:
    - echo $VERSION
    - CI_COMMIT_BRANCH=$(echo "$CI_COMMIT_BRANCH" | tr '[:upper:]' '[:lower:]')
    - DOCKER_IMAGE=$DOCKER_REPO/$NAME:$CI_COMMIT_BRANCH
    - docker build --pull -f ./Dockerfile -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
