variables:
  NAME: qlt-router

include:
  - template: Code-Quality.gitlab-ci.yml

default:
  tags:
    - docker-ex

stages:
  - prepare
  - build
  - pack
  - test
  - deploy
  - security

version:
  image: davinci1976/docker-ci:unstable
  stage: prepare
  script:
    - ./scripts/setVersion.sh
  artifacts:
    paths:
      - ./.env

build:
  image: golang:buster
  stage: build
  needs:
    - version
  cache:
    paths:
      - .cache/
    key: GO
  script:
    - (test -d /artefacts && ln -s /artefacts ./artefacts) || mkdir -p artefacts
    - ls -l .cache || true
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - make build-rpm
    - ./$NAME version
    - cp $NAME ./artefacts/
  artifacts:
    paths:
      - ./artefacts/$NAME
    expire_in: 2 day

unit-test:
  image: golang:buster
  needs: []
  stage: test
  cache:
    paths:
      - .cache/
    key: GO
  #coverage: "/coverage: \\d+.\\d+% of statements/"
  coverage: "/\\(statements\\)(?:\\s+)?(\\d+(?:\\.\\d+)?%)/"
  script:
    - go install gotest.tools/gotestsum@latest
    - go install github.com/nikolaydubina/go-cover-treemap@latest
    - go get github.com/boumenot/gocover-cobertura
    - make test-unit
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

rpm:
  image: rpmbuild/centos7
  needs:
    - version
    - build
  stage: pack
  script:
    - test -d /artefacts && ln -s /artefacts ./artefacts
    - ./rpm/build-rpm.sh
  artifacts:
    paths:
      - ./artefacts/$NAME*.rpm
    expire_in: 2 day

rpm-tests:
  image: davinci1976/docker-ci:unstable
  needs:
    - version
    - rpm
  stage: test
  script:
    - test -d /artefacts && ln -s /artefacts ./artefacts
    - ./rpm/test-rpm.sh

build-docker:
  image: davinci1976/docker-ci:unstable
  stage: build
  needs:
    - version
  script:
    - docker build --pull -f ./Dockerfile -t $NAME:$CI_COMMIT_SHA .
    - docker run --rm $NAME:$CI_COMMIT_SHA $NAME version
    - docker rmi $NAME:$CI_COMMIT_SHA
