version: '2.2'
services:
  qlt:
    build: .
    tty: true
    environment:
      #SENTINEL_ADDR: "ingestion-lumberjack.branch2.trcblt.com:80"
      #ES_URL: "http://elasticsearch:9200"
      #FILENAME: "/data/sss.json"
      
      #LUMBERJACK_ADDR: logstash:5044
      
      LUMBERJACK_ADDR: ingestion-lumberjack.branch2.trcblt.com:443
      LUMBERJACK_CERT: ./config/qlt-router/lb-cert.pem
      LUMBERJACK_KEY: ./config/qlt-router/lb-cert.key

      #LUMBERJACK_CA: ./config/qlt-router/lb-ca.pem
      
      QLT_PORT: "3333"
      QLT_HOST: "0.0.0.0"

      QLTS_PORT: "3334"
      QLTS_HOST: "0.0.0.0"
      QLTS_CERT: "./certs/server.pem"
      QLTS_KEY: "./certs/server.key"


    volumes:
    - "./data:/data"
    - "./config:/config"
    - "./certs:/certs"
    ports:
    - 8090:80
    - 3333:3333
    - 3334:3334

  cft1:
    image: registry.dctest.docker-cluster.axwaytest.net/mft/docker-cft:3.3.2
    hostname: cft1
    environment:
      CFT_CG_ENABLE: "No"
      CFT_CG_HOST: fchost
      CFT_CG_PORT: 12553
      CFT_CG_SHARED_SECRET: Secret01
      CFT_CG_PERIODICITY: "30"
      CFT_HOST: cft
      CFT_PORT: 8093
      CFT_GROUP: Production.Linux
      CFT_KEY: "cat /run/secrets/cft-license"
      CFT_POLICY: ""
      CFT_PESIT_PORT: 1761
      CFT_PESITSSL_PORT: 8092
      CFT_FQDN:               cft
      CFT_INSTANCE_ID:        cft_docker_01
      CFT_INSTANCE_GROUP:     dev.docker
      CFT_CATALOG_SIZE:       1000
      CFT_COM_SIZE:           1000
      CFT_COMS_PORT:          1765
      CFT_COPILOT_PORT:       1766
      CFT_COPILOT_CG_PORT:    1767
      CFT_RESTAPI_PORT:       1768
      CFT_CG_ENABLE:          "YES"
      CFT_CG_POLICY:          ""
      CFT_JVM:                1024
      CFT_CFTDIRRUNTIME:      "./data/runtime"
    #ports:
      #- "1761-1762:1761-1762"
      #- "1765:1765"
      #- "1766:1766"
      #- "1767:1767"
      #- "1768:1768"
      #- "8092:8092"
    #secrets:
    #  - cft-license
    volumes:
#      - "cft_data:/home/cft/data"
      - ./licenses/cft-license.txt:/run/secrets/cft-license   

  cft2:
    extends:
      service: cft1
    hostname: cft2
    environment:
      CFT_INSTANCE_ID:        cft_docker_02
  
  cft3:
    extends:
      service: cft1
    hostname: cft3
    environment:
      CFT_INSTANCE_ID:        cft_docker_03

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
    - 5601:5601
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0 #:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    #networks:
    #  - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash:7.2.0
    volumes:
    - ./config/logstash-pipeline:/usr/share/logstash/pipeline

  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    - /prometheus-data

#volumes:
#  cft_data:
#    driver: "local"
  
  
#secrets:
#  cft-license:
#    file: ./licenses/cft-license.txt

