FROM registry.suse.com/suse/sle15:latest
RUN zypper --non-interactive update && zypper --non-interactive install tar gzip systemd && zypper --non-interactive clean all

COPY ./artefacts/*.rpm .
ARG NAME
RUN rpm -i ./${NAME}*.rpm
COPY rpm/tests /config/tests
