FROM redhat/ubi8-minimal
RUN microdnf update && microdnf install findutils procps tar gzip systemd && microdnf clean all

COPY ./artefacts/*.rpm .
RUN ls ./artefacts
RUN ls .
RUN rpm -i ./*rpm
COPY rpm/tests /config/tests
