FROM registry.suse.com/suse/sle15:latest
RUN zypper --non-interactive update && zypper --non-interactive install tar gzip systemd procps && zypper --non-interactive clean all

COPY ./artefacts/*.rpm /
COPY rpm/tests /config/tests
