FROM redhat/ubi8-minimal
RUN microdnf update && microdnf install findutils procps tar gzip systemd && microdnf clean all

COPY ./artefacts/*.rpm .
ARG NAME
RUN rpm -i ./${NAME}*.rpm
COPY rpm/tests /config/tests
