{{- if .Values.eventrouter.configuration }}
{{- if .Values.eventrouter.configuration.createConfigMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "event-router.fullname" . }}-{{ .Values.eventrouter.configuration.fileName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "event-router.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 4 }}
    {{- end }}
data:
  {{ .Values.eventrouter.configuration.fileName | quote }} : |-
{{ .Files.Get .Values.eventrouter.configuration.localFile | indent 4}}
{{ end -}}
{{- end }}
