{{- $fullName := include "event-router.fullname" . -}}
{{- $labels := include "event-router.labels" . -}}

{{- if .Values.eventrouter.certificates }}
 {{- range .Values.eventrouter.certificates }}
  {{- if .createSecretFile }}
   {{- if .localFile }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ .secretName }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- $labels | nindent 4 }}
    {{- if $.Values.podLabels }}
    {{- toYaml $.Values.podLabels | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{ .secretName | quote }} : |-
    {{ $.Files.Get .localFile | b64enc }}
   {{ end -}}
  {{- end }}
 {{- end }}
{{- end }}
