{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "event-router.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{- toYaml .Values.podLabels | nindent 4 }}
    {{- end }}
  name: {{ template "event-router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- end }}
