apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-router.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "event-router.labels" . | nindent 4 }}
    {{- if .Values.podLabels }}
    {{ toYaml .Values.podLabels }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
  {{- end }}
  ports:
    - name: general
      port: {{ int .Values.service.port }}
      {{- if .Values.service.targetPort }}
      targetPort: {{ int .Values.service.targetPort }}
      {{- end }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ int .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "event-router.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
