FROM alpine:edge AS build
RUN apk add --no-cache --update go wget gcc g++ make git
WORKDIR /app/src
RUN wget https://go.dev/dl/go1.24.1.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.24.1.linux-amd64.tar.gz
RUN export PATH=/usr/local/go/bin:$PATH
RUN go version
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
RUN --mount=type=cache,target=/go/pkg/mod go install gotest.tools/gotestsum@latest
ENV PATH="/root/go/bin:${PATH}"
RUN --mount=type=cache,target=/go/pkg/mod go install github.com/nikolaydubina/go-cover-treemap@latest
RUN --mount=type=cache,target=/go/pkg/mod go get github.com/boumenot/gocover-cobertura

COPY .git/ .env Makefile ./
COPY ./src/ ./src/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    make build-musl
RUN /app/src/event-router version
