FROM alpine:edge AS build
RUN apk add --no-cache --update go gcc g++ make git
WORKDIR /app/src
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
RUN --mount=type=cache,target=/go/pkg/mod go install gotest.tools/gotestsum@latest
ENV PATH="/root/go/bin:${PATH}"
RUN --mount=type=cache,target=/go/pkg/mod go install github.com/nikolaydubina/go-cover-treemap@latest
RUN --mount=type=cache,target=/go/pkg/mod go get github.com/boumenot/gocover-cobertura

COPY .git/ .env Makefile ./
COPY ./src/ ./src/

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    make build-musl
RUN /app/src/event-router version


