#!/bin/sh

# Testing EULA
ACCEPT_GENERAL_CONDITIONS=`echo $ACCEPT_GENERAL_CONDITIONS | tr '[a-z]' '[A-Z]'`
if [ "$ACCEPT_GENERAL_CONDITIONS" = "YES" ]; then
    echo "General Terms and Conditions accepted."
else
    echo "General Terms and Conditions not accepted. EXIT"
    exit 1
fi

whoami
if [ $? -ne 0 ]; then
    if [ -w /etc/passwd ]; then
        echo "${USER_NAME:-default}:x:$(id -u):0:${USER_NAME:-default} user:${HOME}:/sbin/nologin" >> /etc/passwd
        echo "user ${USER_NAME:-default} ($(id -u)) created"
    fi
fi

exec "$@"
