flows:
  - name: "csv-xml-2-xml-qltclient"
    disable: true
    description: ""
    flow:
      - name: "file_csv_producer"
      - name: "convert" #/*,scaleOrdered: 4*/
      - name: "control"
      - name: "qlt_client_consumer"
