# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2023 Axway Software SA and its affiliates. All rights reserved.
#
#

version: "3.5"

services:
  eventrouter:
    image: eventrouter/eventrouter:3.0

    environment:
      # 
      # Parameters referenced in the template configuration
      # 
      ER_INSTANCE_ID: "eventrouter-1"
      ER_QLT_SERVER_CERT: /run/secrets/qlt_server_cert.pem
      ER_QLT_SERVER_KEY: /run/secrets/qlt_server_key.pem
      ER_QLT_SERVER_CA: /run/secrets/qlt_server_ca.pem
      ER_SENTINEL_CA: /run/secrets/sentinel_ca.pem
      ER_KAFKA_SERVER_CA: /run/secrets/kafka_ca.pem
      ER_KAFKA_CLIENT_CERT: /run/secrets/kafka_client_cert.pem
      ER_KAFKA_CLIENT_KEY: /run/secrets/kafka_client_key.pem
      # 
      # General parameters
      # 
      ER_LOG_LEVEL: "info" # supported values: trace, debug, info, warn, error, fatal
      #ER_CONFIG_FILE: "./event-router.yml" # path to config file
      #ER_PORT: "8080" # http port
      #ER_HOST: "0.0.0.0" # http host
      #ER_LOG_USE_LOCALTIME: "false" # log uses local time

    ports:
    - "1325:1325" # same ports as the ones configured as input in event-router.yml configuration
    - "8080:8080" # port used to expose Prometheus metrics: http://host:8080/metrics

    volumes:
      # volume used to map the Event Router configuration.
      - ./conf/event-router.yml:/opt/axway/event-router.yml
      # volume used to persist file readers and writers data.
      - eventrouter_data:/opt/axway/data

    # Uncomment the following lines to enable the necessary secrets
    #secrets:
    #- qlt_server_cert.pem
    #- qlt_server_key.pem
    #- qlt_server_ca.pem
    #- sentinel_ca.pem
    #- kafka_server_ca.pem
    #- kafka_client_cert.pem
    #- kafka_client_key.pem

volumes:
  eventrouter_data:
    driver: local

# Uncomment the following lines to map the necessary certificates as secrets.
#secrets:
  #qlt_server_cert.pem:
  #  file: ./conf/qlt_server_cert.pem
  #qlt_server_key.pem:
  #  file: ./conf/qlt_server_key.pem
  #qlt_server_ca.pem:
  #  file: ./conf/qlt_server_ca.pem
  #sentinel_ca.pem:
  #  file: ./conf/sentinel_ca.pem
  #kafka_server_ca.pem:
  #  file: ./conf/kafka_ca.pem
  #kafka_client_cert.pem:
  #  file: ./conf/kafka_client_cert.pem
  #kafka_client_key.pem:
  #  file: ./conf/kafka_client_key.pem
