# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2021 Axway Software SA and its affiliates. All rights reserved.
#
## AMPLIFY Sentinel Event Router 2.4.0 SP3 Docker image
#
# Building with:
# docker-compose up -d

version: "3.5"

services:
  eventrouter:
    image: eventrouter/eventrouter:2.4.0-SP3

    environment:
      # Change RECONFIG value to force the reinitialization of configuration
      ER_RECONFIG:               "NO"
      # Time between healthchecks. In seconds.
      ER_HEALTHCHECK_INTERVAL:  10
      ### AGENT PARAMETERS
      ER_NAME:                  SentinelEventRouter
      ER_LOG_LEVEL:             0 # 0 -> 4
      ER_MESSAGE_SIZE:          10000
      ER_MAX_MESSAGES:          10000
      ER_RELAY:                 0
      ### TCP SOURCE
      ER_INCOMING_MAX:          1000
      ER_PORT:                  1325
      ER_USE_SSL:               "NO"
      # Uncomment the next 2 lines to enable SSL and configure server certificate.
      # See also secrets sections.
      # The certificate must refer to a PKCS12 certificate.
      #ER_CERTIFICATE_FILE:      "/run/secrets/eventrouter.p12"
      #ER_CERT_PASSWORD_FILE:    "/run/secrets/eventrouter_p12.pwd"
      ER_SSL_CIPHER_SUITE:      "156,60,47"
      ER_SSL_VERSION_MIN:       "tls_1.2"

      ### TARGETS
      # This block can be repeted as many time as there are targets.
      # Just increment the number in the variables' names (TARGET1 -> TARGET2, TARGET3, ...)
      TARGET1_NAME:             SENTINEL
      TARGET1_LOG_LEVEL:        0 # 0 -> 4
      TARGET1_PORT:             1305
      TARGET1_ADDRESS:          sentinel
      TARGET1_TIMEOUT:          5
      TARGET1_SHORT_WAIT:       10
      TARGET1_LONG_WAIT:        300
      TARGET1_JUMP_WAIT:        20
      TARGET1_KEEP_CONNECTION:  30
      TARGET1_HEARTBEAT:        0
      TARGET1_USE_SSL_OUT:      "NO"
      TARGET1_SSL_CIPHER_SUITE: "156,60,47"
      TARGET1_SSL_VERSION_MIN:  "tls_1.2"
      # Uncomment the next line to customize the Target1 CA certificate.
      # Needed if TARGET1_USE_SSL_OUT is YES.
      # See also secrets sections.
      #TARGET1_CA_CERT:          "/run/secrets/target1_ca_cert.pem"

      #####
      # User defined target.xml
      #USER_TARGET_XML:         "/opt/app/custom/target.xml"

    ports:
    # ER_PORT:
    - "1325:1325"

    volumes:
    # Docker local volume where the runtime data is stored
    - eventrouter_data:/opt/axway/data
    # Localhost mapped volume where customization files are located.
    # Uncomment this for enabling customization.
    #- ./conf:/opt/app/custom:ro

    #secrets:
    # Uncomment these 2 lines for configuring the Event Router certificate.
    #- eventrouter.p12
    #- eventrouter_p12.pwd
    # Uncomment this for customizing the Target1 CA certificate.
    #- target1_ca_cert.pem

#secrets:
  # Files containig the Event Router certificate and password.
  # Uncomment the next four lines to customize the Sentinel Event Router server certificate.
  #eventrouter.p12:
  #    file: ./conf/eventrouter.p12
  #eventrouter_p12.pwd:
  #    file: ./conf/eventrouter_p12.pwd
  # File containig the CA certificate of Target1.
  # Uncomment the next two lines to specify the CA certificate.
  #target1_ca_cert.pem:
  #    file: ./conf/target1_ca_cert.pem

volumes:
  eventrouter_data:
    driver: local
