# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2021 Axway Software SA and its affiliates. All rights reserved.
#
## AMPLIFY Sentinel Event Router 2.4.0 SP3 Docker image
#
# Building with:
# docker-compose up -d

# Test scenario:     
#                   -> middle ER           \
#  UA  -> 1st ER <                           -> last ER 
#                   -> backup of middle ER /
# We stop middle ER during test. Last ER should have all expected messages
#



version: "3.5"

services:
  sut:
    build: ../test
    depends_on:
    - eventrouter_first
    - eventrouter_middle
    - eventrouter_middle_backup
    - eventrouter_last
    
    environment:
      UA_NAME:                 SentinelUniversalAgent
      FIRST_TARGET_NAME:       test_er_first
      FIRST_TARGET_PORT:       1325
      MIDDLE_TARGET_NAME:      test_er_middle
      MIDDLE_TARGET_PORT:      1326
      M_BACKUP_TARGET_NAME:    test_er_middle_backup
      M_BACKUP_TARGET_PORT:    1327
      LAST_TARGET_NAME:        test_er_last
      LAST_TARGET_PORT:        1328
    container_name:            test_sut_1
    volumes:
    - eventrouter_first_data:/opt/axway/data_first
    - eventrouter_middle_data:/opt/axway/data_middle
    - eventrouter_backup_data:/opt/axway/data_backup
    - eventrouter_last_data:/opt/axway/data_last
    - /var/run/docker.sock:/var/run/docker.sock
    
  eventrouter_last:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_er_last

    environment:
      ER_NAME:                  SentinelEventRouter4
      ER_PORT:                  1328
      ER_LOG_LEVEL:             0
      ER_USE_SSL:               "NO"

      
      TARGET1_NAME:            SENTINEL
      TARGET1_LOG_LEVEL:       0
      TARGET1_PORT:            1305
      TARGET1_ADDRESS:         sentinel
      TARGET1_USE_SSL_OUT:     "NO"
      
    ports:
    - "1328:1328"

    volumes:
    - eventrouter_last_data:/opt/axway/data
    
  eventrouter_middle:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_er_middle

    environment:
      ER_NAME:                  SentinelEventRouter2
      ER_PORT:                  1326
      ER_LOG_LEVEL:             0
      ER_USE_SSL:               "NO"
      
      TARGET1_NAME:             SENTINEL
      TARGET1_LOG_LEVEL:        0
      TARGET1_PORT:             1328
      TARGET1_ADDRESS:          test_er_last
      TARGET1_TIMEOUT:          5
      TARGET1_SHORT_WAIT:       10
      TARGET1_LONG_WAIT:        300
      TARGET1_JUMP_WAIT:        20
      TARGET1_KEEP_CONNECTION:  30
      TARGET1_HEARTBEAT:        0
      TARGET1_USE_SSL_OUT:      "NO"
      
    ports:
    - "1326:1326"

    volumes:
    - eventrouter_middle_data:/opt/axway/data
        
  eventrouter_middle_backup:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_er_middle_backup

    environment:
      ER_NAME:                  SentinelEventRouter3
      ER_PORT:                  1327
      ER_LOG_LEVEL:             1
      ER_USE_SSL:               "NO"
      
      TARGET1_NAME:             SENTINEL
      TARGET1_LOG_LEVEL:        0
      TARGET1_PORT:             1328
      TARGET1_ADDRESS:          test_er_last
      TARGET1_TIMEOUT:          5
      TARGET1_SHORT_WAIT:       10
      TARGET1_LONG_WAIT:        300
      TARGET1_JUMP_WAIT:        20
      TARGET1_KEEP_CONNECTION:  30
      TARGET1_HEARTBEAT:        0
      TARGET1_USE_SSL_OUT:      "NO"
      
    ports:
    - "1327:1327"

    volumes:
    - eventrouter_backup_data:/opt/axway/data

  eventrouter_first:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_er_first

    environment:
      ER_NAME:                  SentinelEventRouter1
      ER_PORT:                  1325
      ER_LOG_LEVEL:             0
      ER_USE_SSL:               "NO"

      DEFAULT_LOG_LEVEL:        0
      
      TARGET1_NAME:             SENTINEL
      TARGET1_LOG_LEVEL:        1
      TARGET1_PORT:             1326
      TARGET1_ADDRESS:          test_er_middle
      TARGET1_BACKUP_PORT:      1327
      TARGET1_BACKUP_ADDRESS:   test_er_middle_backup
      TARGET1_TIMEOUT:          5
      TARGET1_SHORT_WAIT:       7
      TARGET1_LONG_WAIT:        100
      TARGET1_JUMP_WAIT:        10
      TARGET1_KEEP_CONNECTION:  10
      TARGET1_HEARTBEAT:        0
      TARGET1_USE_SSL_OUT:      "NO"
      
    ports:
    - "1325:1325"

    volumes:
    - eventrouter_first_data:/opt/axway/data

volumes:
  eventrouter_first_data:
    driver: local
  eventrouter_middle_data:
    driver: local
  eventrouter_backup_data:
    driver: local
  eventrouter_last_data:
    driver: local
