# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2021 Axway Software SA and its affiliates. All rights reserved.
#
## AMPLIFY Sentinel Event Router 2.4.0 SP3 Docker image
#
# Building with:
# docker-compose up -d

version: "3.5"

services:
  sut:
    build: ../test
    depends_on:
    - eventrouter1
    - eventrouter2
    
    environment:
      UA_NAME:                 SentinelUniversalAgent
      TARGET_NAME:             test_eventrouter_1
      TARGET_PORT:             1325
      TARGET2_NAME:            test_eventrouter_2
      TARGET2_PORT:            1326
    container_name:            test_sut_1
    volumes:
    - eventrouter1_data:/opt/axway/data1
    - eventrouter2_data:/opt/axway/data2
    
  eventrouter1:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_eventrouter_1

    environment:
      ER_NAME:                 SentinelEventRouter1
      ER_PORT:                 1325
      ER_LOG_LEVEL:            1
      
      TARGET1_NAME:            SENTINEL
      TARGET1_LOG_LEVEL:       1
      TARGET1_PORT:            1326
      TARGET1_ADDRESS:         test_eventrouter_2
      TARGET1_TIMEOUT:         5
      TARGET1_SHORT_WAIT:      10
      TARGET1_LONG_WAIT:       300
      TARGET1_JUMP_WAIT:       20
      TARGET1_KEEP_CONNECTION: 30
      TARGET1_HEARTBEAT:       0
      TARGET1_USE_SSL_OUT:     "NO"
      TARGET1_SSL_CIPHER_SUITE: "156,60,47"
      TARGET1_SSL_VERSION_MIN: "tls_1.2"
      # Uncomment the next line to customize the Target1 CA certificate.
      # Needed if TARGET1_USE_SSL_OUT is YES.
      # See also secrets sections.
      #TARGET1_CA_CERT:        "/run/secrets/target1_ca_cert.pem"
      
    ports:
    - "1325:1325"

    volumes:
    - eventrouter1_data:/opt/axway/data

    #secrets:
    # Uncomment this for customizing the Target1 CA certificate.
    #- target1_ca_cert.pem
    
  eventrouter2:
    image: $IMAGE_ER:$DOCKER_TAG
    container_name:            test_eventrouter_2

    environment:
      ER_NAME:                 SentinelEventRouter2
      ER_PORT:                 1326
      ER_LOG_LEVEL:            1
      ER_USE_SSL:              "NO"
      # Uncomment the next 2 lines to enable SSL and configure server certificate.
      # See also secrets sections.
      # The certificate must refer to a PKCS12 certificate.
      #ER_CERTIFICATE_FILE:    "/run/secrets/eventrouter.p12"
      #ER_CERT_PASSWORD_FILE:  "/run/secrets/eventrouter_p12.pwd"
      ER_SSL_CIPHER_SUITE:     "156,60,47"
      ER_SSL_VERSION_MIN:      "tls_1.2"
      
      TARGET1_NAME:            SENTINEL
      TARGET1_LOG_LEVEL:       0
      TARGET1_PORT:            1305
      TARGET1_ADDRESS:         sentinel
      TARGET1_USE_SSL_OUT:     "NO"
      
    ports:
    - "1326:1326"

    volumes:
    - eventrouter2_data:/opt/axway/data

    #secrets:
    # Uncomment these 2 lines for configuring the Event Router certificate.
    #- eventrouter.p12
    #- eventrouter_p12.pwd
    
#secrets:
  # Files containig the Event Router certificate and password.
  # Uncomment the next four lines to customize the Sentinel Event Router server certificate.
  #eventrouter.p12:
  #    file: ./conf/eventrouter.p12
  #eventrouter_p12.pwd:
  #    file: ./conf/eventrouter_p12.pwd
  # File containig the CA certificate of Target1.
  # Uncomment the next two lines to specify the CA certificate.
  #target1_ca_cert.pem:
  #    file: ./conf/target1_ca_cert.pem

volumes:
  eventrouter1_data:
    driver: local
  eventrouter2_data:
    driver: local
